uktrade/stream-zip

- README.md
- stream_zip.py
- test_stream_zip.py
This is specifically for ODS files, since the mimetype file is meant to be first in the ZIP, and not compressed
> feat: support no compression

- requirements-dev.txt
- stream_zip.py
Primarily for simplicity - to reduce the differences between the ZIP64 and the NO_COMPRESSION cases
> feat: don't output unused local extra field

- README.md
- stream_zip.py
- test_stream_zip.py
Realistically wouldn't hit the limits on ZIP64, but it's much more possible to hit the ZIP limits, and so offer a "nicer" Exception interface for this case.
> feat: raise exceptions if sizes would cause overflow

- README.md
- stream_zip.py
- test_stream_zip.py
This is for clarity, and to allow in future having both NO_COMPRESSION_32 and NO_COMPRESSION_64, to allow clients to fully specify that they do not want any _64 code data.
Note that LibreOffice doesn't support zip64 at the time of writing, so this is still an issue. This is not just for "legacy" software.
> feat!: rename constants

- README.md
- stream_zip.py
This I think is a reasonable way of addressing the need for large files that should both not be buffered in memory, and not compressed, as reported in https://github.com/uktrade/stream-zip/issues/17
> feat: allow specification of zlib compressobj

- stream_zip.py
This was added in https://github.com/uktrade/stream-zip/commit/62f8cf1ee242f7d9fe1467fe9a93b20164764068, but it might not really have ever been needed, so removing it saves a few bytes. And stronger than that, https://github.com/libarchive/libarchive/issues/1834 gives an argument that it even makes the ZIP file invalid.
To give even more weight to the argument that this is ok, I made a few Zip64 files with data descriptors with InfoZIP. They did not have local Zip64 extra fields. If this were a problem, it probably would have been discovered by now.
> feat: no need for local zip64 extra when streaming

- .github/workflows/tests.yml
- .gitignore
- CONTRIBUTING.md
- install-libarachive.sh
- stream_zip.py
- test_stream_zip.py
This reverts commit 1130fdcb5f8a068c194392fdf5b0d8b6769a8928, "feat: no need for local zip64 extra when streaming"
It was thought that there was no need for the ZIP_64 "extra" section in the local header. Tests ran fine without it, and there was an argument that having it made the ZIP file invalid at https://github.com/libarchive/libarchive/issues/1834. However, it was found in https://github.com/uktrade/stream-zip/issues/27 that it caused an error on OSX's Archive Utility:
> Error 79 - Inappropriate file type or format
and a very similar error in libarchive's bsdcpio
> cpio: Inconsistent uncompressed size: 12 in central directory, 4294967295 in local header: Inappropriate file type or format
or in some situations
> cpio: ZIP uncompressed data is wrong size (read 12, expected 0)
> fix: 'Inappropriate file type or format' in Archive Utility and bsdcpio

- .github/workflows/tests.yml
- setup.py
Suspect this wasn't done earlier since it seemed tricky to test this version on CircleCI. However, it seems a bit easier on GitHub actions where the tests now run
https://github.com/uktrade/stream-zip/issues/32
> deps: support Python >= 3.7.1

- stream_zip.py
Linux unzip won't extract symlinks properly unless a special `create_system` value is set in `version_made_by`. Python's ZipFile already does this, and this change is intended to behave the same way: set `create_system` to 3 for non-Windows OS.
> feat: add symlink support

- docs/getting-started.md
- requirements-dev.txt
- stream_zip.py
- test_stream_zip.py
This allows client code to not worry about which ZIP_32 or ZIP_64 mode is needed, as long as it has the uncompressed size of the file.
Most discussion is in https://github.com/uktrade/stream-zip/pull/42
> feat: add ZIP_AUTO mode

- docs/getting-started.md
- docs/modes.md
It looks like mkdocs has slightly different rules on indentation in lists than in GitHub
> docs: fix indentation in mkdocs

- stream_zip.py
It was assumed that memLevel=9 should stick to the bounds calculated for memLevel=8, but this is wrong https://github.com/madler/zlib/issues/822
> fix: use default memLevel in ZIP_AUTO to more robustly stick to bounds

- stream_zip.py
- test_stream_zip.py
This was missed from previous work on ZIP_AUTO mode.
There is still one value that is not auto upgraded to Zip64 - central_directory_size. But this limit is 4GiB in Zip32, which is pretty enormous for a central directory. I think it's fine to leave that for now.
> fix: auto upgrade central directory if too many files in ZIP_AUTO mode

- stream_zip.py
The aim here is for clients to fail fast
> feat: raise central directory-related overflow exceptions a bit earlier

- docs/advanced-usage.md
- docs/exceptions.md
- docs/getting-started.md
- docs/methods.md
- stream_zip.py
- test_stream_zip.py
This is inspired by https://github.com/uktrade/stream-zip/issues/55 and https://github.com/uktrade/stream-zip/pull/56 that describe issues with storing empty directories. However, rather than any behaviour change, this PR slightly refactors code and (hopefully) improves documentation regarding what was known as the perms/permissions option, and how to make empty directories.
The perms/permissions option is more accurately a "mode", as in, the unix/linux file mode, that describes not only permissions, but the type of file, e.g. regular file, directory, or symbolic link. Since this is now "mode", what was the "mode", the ZIP_32/ZIP-64-ness of member files is now known as the "method". This was already "method" in some of the code, and is more consistent with APPNOTE.
The tests in this PR …
> docs: change perms to mode, mode to method, and document how to make empty directories and symbolic links

- docs/advanced-usage.md
- stream_zip.py
- test_stream_zip.py
The original ZIP format had two problems with how it stored modification time
- It can't be more accurate than to within 2 seconds
- It is treated as a local time
This PR addresses both of these by storing the time in a `UT` extra field.
This field is added by default, but is omitted if `extended_timestamps=False` is passed to `stream_unzip`. This is not just a "just in case" thing - when using stream-zip to make Open Document files such as in https://github.com/uktrade/stream-write-ods, to pass the validation at https://odfvalidator.org/, the files must _not_ have extended timestamps.
Closes https://github.com/uktrade/stream-zip/issues/57
> feat: more accurate modification timestamps for clients that support it

- docs/exceptions.md
- docs/methods.md
- stream_zip.py
- test_stream_zip.py
This is inspired by https://github.com/uktrade/stream-zip/issues/58, but it doesn't fully address everything mentioned. Specifically, it doesn't make it possible to stream write uncompressed files without knowing the uncompressed size and CRC 32 ahead of time. I'm very torn on whether to allow stream writing uncompressed files without these, since it would mean that such files cannot be stream unzipped.
> feat: stream-writable uncompressed member files with known size and crc32

- docs/exceptions.md
Have changed my mind a few times on this, but think it's clearer to include the term hierarchy
> docs: fix and clarify exception hierarchy

- docs/async-interface.md
- mkdocs.yml
This was discussed in https://github.com/uktrade/stream-zip/issues/87. Maybe down the line this code will be brought into stream-zip, or an interface created that doesn't use threads under the hood. However for now, documenting how to work with what there is I think is the quickest/easiest step forward.
> docs: document how to make an async interface

- docs/output-examples.md
This removes the code from a recipe - converting the iterable output to a file-like object, and replaces it with an import from https://github.com/uktrade/to-file-like-obj
This should hopefully make it just a touch easier for people to use the recipes. It's deliberate to not include the to-file-like-obj in the dependencies of this project in order to keep the dependencies down - not everyone will need it.
> docs: reference to-file-like-obj package rather than repeating code

- README.md
This adds a badge showing the current package version on conda-forge, with a link to it at https://anaconda.org/conda-forge/stream-zip
stream-zip has been recently added to conda-forge via https://github.com/conda-forge/staged-recipes/pull/24588, with its feedstock repo at https://github.com/conda-forge/stream-zip-feedstock, so this is done for slightly easier discoverability that it's on conda forge and an option for users.
This is also done for consistency with the sibling project, stream-unzip, which has a badge at the top of its README at https://github.com/uktrade/stream-unzip
> docs: add badge to condo-forge package

- .github/workflows/test.yml
- README.md
- docs/features.md
- docs/get-started.md
- pyproject.toml
- stream_zip.py
- test_stream_zip.py
This adds AES-2 encryption as requested/discussed in https://github.com/uktrade/stream-zip/issues/93 and defined at https://www.winzip.com/en/support/aes-encryption/
For now, AES-2 is used over AES-1 to prevent leakage of information via CRC-32 for small files, at the price of not having a checksum on the uncompressed plain text data (although there is an HMAC check on the encrypted compressed data as part of AES-2). In a later change, we should be able to make it AES-1 for larger files as recommended at https://www.winzip.com/en/support/aes-encryption/, but not doing this now to keep this change reasonably small.
> feat: AES-2 encryption

- docs/get-started.md
- test_stream_zip.py
This changes documentation in what is now the "Password protection / encryption" section. It also changes tests to make sure the example in the documentation works, and makes the tests themselves use better practices, in case they are seen down the line as examples to follow in the real world.
Specifically it links to https://crypto.stackexchange.com/a/109269/113464 which serves as a bit of a warning, but also contains some advice. And, it makes the password in the example longer and random.
It does not implement all the recommendations at https://crypto.stackexchange.com/a/109269/113464 at least for now to keep this change small while I consider them - they may come in later changes (e.g. renaming password to passphrase or generating a default ourselves).
This is done as part of the …
> docs: another link to warnings and better examples on password generation

- docs/advanced-usage.md
- docs/get-started.md
Because the encryption has some gotchas and shouldn't be used if not informed, think it's more appropriate to be in the advanced section.
This is done in response to the request/discussion at https://github.com/uktrade/stream-zip/issues/93
> docs: move information on encryption to the advanced section

- README.md
- docs/features.md
This mentions AES-256 in the feature list so it's very clear that this isn't ZipCrypto up front, as well as the encryption strength, and to hint that the encryption strength is not configurable, so people aren't surprised.
> docs: be explicit on the underlying encryption used when password protecting

- docs/index.md
This adds the order of 0 to the index/homepage
It's a speculative attempt to fix the slightly non-deterministic sort order of _non_ homepages.
> docs: add order of 0 to index/homepage

- docs/sass/_settings.scss
This was incorrectly left out of the commit at 48b625b60bf6bd7d02380ea9084eefbb73c6dfca
It:
- Uses system-ui rather than the GDS Transport font, which I think we shouldn't be using since this isn't a GOV.UK services
- Fixes height/spacing in the header
> docs: use system font, and fix layout of header

- README.md
- docs/async-interface.md
- docs/features.md
- stream_zip.py
- test_stream_zip.py
This brings the async example from the documentation into the codebase proper.
This is inspired by the PR and conversation at https://github.com/uktrade/stream-unzip/pull/80. To avoid duplication, threads are used to use the sync code without blocking the event loop.
> feat: async interface

- README.md
- docs/features.md
I think I was conflating a few different things when writing about avoiding blocking the event loop as a reason for using threads in the async implementation.
The reasoning for using threads is more:
- async_stream_zip takes async iterables
- which means if delegating to stream_zip, it would need to call async functions like `anext` or `__anext__` from sync functions, and wait for them to complete.
- there is only really one choice for this that works/avoids deadlock: run_coroutine_threadsafe.
- which means this call must be in a different thread
> docs: avoid mentioning blocking the event loop in async implementation

- package-lock.json
- package.json
This bumps all packages used in building docs, and removes force-resolutions which is no longer needed.
Mostly triggered by `npm ci` taking many hours in GitHub Actions.
> build(deps): bump docs-building packages

- .github/workflows/test.yml
- pyproject.toml
- stream_zip.py
Inspired by the discussion at https://github.com/uktrade/stream-zip/discussions/120 adding in a few type annotations.
Keeping it minimal for the first pass just to get things in. Expecting more/stricter types/checking in later changes.
> refactor: initial type annotations

- stream_zip.py
This adds basic type annotation to async_stream_zip (and another internal function). And there is a bit of rejigging to get types to check, but other than adding return types the client-facing API should be the same.
This is inspired by https://github.com/uktrade/stream-zip/discussions/120
There will probably be more changes after this PR.
> feat: type annotate async function (and an internal function)

- stream_zip.py
Inspired by https://github.com/uktrade/stream-zip/discussions/120, this carries on better annotating the types involved in stream-zip.
In this case, giving stricter types to the files iterable
> feat: better annotate the member files/methods

- stream_zip.py
Each "Method" now derives from a base class, that has a "get" function to get the internal tuple that controls its file's behaviour. This makes it possible for the same class to both have such a method, _and_ be callable to get a different method, which is how the current NO_COMPRESSION_* types work as methods but also as a callable to return a different method.
(Maybe this can be turned into a Protocol in future changes)
> feat: a Method has a clearer definition (that passes strict type checking)

- .github/workflows/test.yml
- stream_zip.py
This changes the internal tuple type to make the uncompressed size and crc_32 non optional ints which makes it possible to pass type checking without any ifs or casts. This is still slightly odd maybe because it means we hard code them to 0 when they're not used. A "better" structure might be to have some sort of more dynamic structure to avoid this - maybe multiple tuples or a more complex class. However, suspect this is still a small step forward since it allows strict type checking.
> feat: type annotations now allow strict type checking

- stream_zip/__init__.py
Maybe could replace with with a custom Protocol in a later version, but this is the smallest step that sorts some type checking issues.
> feat: avoid mypy errors about empty body of an abstract method

- .github/workflows/deploy-package-to-pypi.yml
The source does not actually include the correct release version to avoid having to change the source code based on the current or next version. While this is maybe odd, it makes releasing quite easy. However, as https://github.com/uktrade/stream-zip/issues/136 this makes it slightly harder to release for Debian.
So we make a version of the source code that has the correct release version, and add it to the GitHub release. This makes it so any tinkering with versions is just done in this repository.
Bumping the checkout version just by the by
> ci: release process now includes a file with the source, but modified with correct version

- .github/workflows/deploy-package-to-pypi.yml
Getting an error from GitHub actions:
> tar: .: file changed as we read it
Which might be because the archive .tar.gz is being created in the directory being archived. Creating the file first and then excluding it should sort this.
> ci: fix creating .tar.gz of source but versioned

- .github/workflows/deploy-package-to-pypi.yml
Apparently the GitHub CLI needs the GH_TOKEN environment variable
> ci: fix auth error when editing release from GitHub actions

- .github/workflows/test.yml
- pyproject.toml
- test_stream_zip.py
Fixes https://github.com/uktrade/stream-zip/issues/146
Includes loosening the constraints on versions used to run tests in CI (e.g. pytest, coverage) since the older versions don't seem to work on newer Python. Specifically, coverage 6.2 bombs out with an error on Python 3.11)
> tests: fix for release candidates (and test on more versions of Python)
